### ISSUE TITLE
Old resample version for noarch

### ISSUE THREAD

**Issue by HDembinski** [conda-forge/resample-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The noarch installer for resample is an old version 1.0.1, but it should be 1.6.0. The latest resample is pure Python and thus noarch. For some reason, the noarch version is not up-to-date.

https://anaconda.org/conda-forge/resample

### Installed packages

```shell
Irrelevant
```

### Environment info

```shell
Irrelevant
```

**Comment by HDembinski** [comment]
@chrisburr @henryiii Do you have an idea what is going wrong?

**Comment by chrisburr** [comment]
See https://github.com/conda-forge/resample-feedstock/pull/11

**Comment by HDembinski** [comment]
@chrisburr Thank you for the PR!
